export { McpEventType, McpToolEvent } from './events';

export const MCPEAVESDROP_IPC_SOCKET = 'MCPEAVESDROP_IPC_SOCKET';
export const MCPEAVESDROP_REAL_SERVER = 'MCPEAVESDROP_REAL_SERVER';
export const MCPEAVESDROP_REAL_URL = 'MCPEAVESDROP_REAL_URL';
export const MCPEAVESDROP_SERVER_NAME = 'MCPEAVESDROP_SERVER_NAME';
export const MCPEAVESDROP_CONFIG_PATH = 'MCPEAVESDROP_CONFIG_PATH';
export const MCPEAVESDROP_EXT_DIR = 'MCPEAVESDROP_EXT_DIR';
export const MCPEAVESDROP_WRAPPER_VERSION = 'MCPEAVESDROP_WRAPPER_VERSION';
export const MCPEAVESDROP_IDE = 'MCPEAVESDROP_IDE';
export const MCPEAVESDROP_WORKSPACE_SLUG = 'MCPEAVESDROP_WORKSPACE_SLUG';
